# Creates the base infrastructure:
#
#   * Log Analytics and Application Insights
#   * Key Vault
#   * Storage account (the one being monitored for malware)
#   * Container registry

---
trigger:
  - none

stages:
  - stage: Development
    variables:
      - template: ./variables/dev-environment.yml
    jobs:
      - template: ./jobs/create-base-infrastructure-job.yml
        parameters:
          environment: Development
          resourceGroupName: ${{ variables.resourceGroupName }}
          serviceConnectionName: ${{ variables.serviceConnectionName }}
          location: ${{ variables.location }}
          applicationInsightsName: ${{ variables.applicationInsightsName }}
          logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
          keyVaultName: ${{ variables.keyVaultName }}
          storageAccountName: ${{ variables.storageAccountName }}
          storageContainerName: ${{ variables.storageContainerName }}
          containerRegistryName: ${{ variables.containerRegistryName }}
