# This pipeline creates the resources required for malware detection.
#
# This pipeline depends on the following resources created by the base infrastructure pipeline:
#
#   * Application Insights and Log Analytics
#   * Key Vault
#   * Azure Container Registry

---
trigger:
  - none

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - development
    always: true

variables:
  - template: ./variables/dev-environment.yml

jobs:
  - template: ./jobs/create-anti-malware-setup-job.yml
    parameters:
      environment: Development
      resourceGroupName: ${{ variables.resourceGroupName }}
      serviceConnectionName: ${{ variables.serviceConnectionName }}
      location: ${{ variables.location }}
      applicationInsightsName: ${{ variables.applicationInsightsName }}
      logAnalyticsWorkspaceName: ${{ variables.logAnalyticsWorkspaceName }}
      clamAVContainerRepositoryName: ${{ variables.clamAVContainerRepositoryName }}
      buildConfiguration: Release
      imageTag: $(Build.BuildId)
      keyVaultName: ${{ variables.keyVaultName }}
      containerRegistryName: ${{ variables.containerRegistryName }}
      containerRegistryServiceConnectionName: ${{ variables.containerRegistryServiceConnectionName }}
      containerRegistryLoginServerUri: ${{ variables.containerRegistryLoginServerUri }}
      containerGroupName: ${{ variables.containerGroupName }}
      containerInstancesBaseUri: ${{ variables.containerInstancesBaseUri }}
      antiMalwareFunctionAppName: ${{ variables.antiMalwareFunctionAppName }}
      storageAccountName: ${{ variables.storageAccountName }}
      storageContainerName: ${{ variables.storageContainerName }}
      smtpServer: ${{ variables.smtpServer }}
      smtpPort: ${{ variables.smtpPort }}
      smtpDomain: ${{ variables.smtpDomain }}
      malwareNotificationRecipients: ${{ variables.malwareNotificationRecipients }}
