# Variables for the development environment
---
variables:
  # Resource group for all resources deployed by the pipelines
  resourceGroupName: storage-av-demo-rg

  # Prefix for the names of all resources (must be lowercase)
  resourceNamePrefix: storageavdemo0000

  # The Azure Resource Manager service connection name for the resource group
  serviceConnectionName: ${{ variables.resourceGroupName }}-sc

  # Location (region) for all resources created
  location: westeurope

  applicationInsightsName: ${{ variables.resourceNamePrefix }}appinsights
  logAnalyticsWorkspaceName: ${{ variables.resourceNamePrefix }}loganalytics
  keyVaultName: ${{ variables.resourceNamePrefix }}kv

  # Storage account and container to monitor for malware
  storageAccountName: ${{ variables.resourceNamePrefix }}sa
  storageContainerName: testcontainer

  # Container registry for the ClamAV image
  containerRegistryName: ${{ variables.resourceNamePrefix }}acr

  # Container registry service connection name
  containerRegistryServiceConnectionName: ${{ variables.containerRegistryName }}-sc

  containerRegistryLoginServerUri: ${{ variables.containerRegistryName }}.azurecr.io

  # The name of the container group in Azure Container Instances to run the ClamAV image in
  containerGroupName: ${{ variables.resourceNamePrefix }}avaci

  containerInstancesBaseUri: ${{ variables.containerGroupName }}.${{ variables.location }}.azurecontainer.io
  clamAVContainerRepositoryName: clamav

  # The name of the Azure Function App monitoring the storage account
  antiMalwareFunctionAppName: ${{ variables.resourceNamePrefix }}avaf

  # The notification settings for an event when malware is detected
  # The solution will work even if the Office/Outlook settings are not configured properly,
  # but will throw an error in the logs
  malwareNotificationRecipients: "dick.hallorann@overlookhotel.com,jack.torrance@overlookhotel.com"
  smtpServer: "smtp.office365.com"
  smtpPort: "587"
  smtpDomain: "outlook.com"
